[package]
name = "entry_put_ext"
version = "0.1.0"
authors = ["Nossie531"]
edition = "2021"
description = "Map entry extension for put operations."
repository = "https://github.com/nossie531/entry_put_ext"
license = "MIT OR Apache-2.0"
keywords = ["map", "entry", "extension"]
